#!/usr/bin/env php
<?php

use Scratch\Commands\BuildCommand;
use Scratch\Commands\InitCommand;
use Scratch\Commands\SampleCommand;
use Scratch\Commands\SortContentCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Start the console application.
 */
$app = new Application('Scratch', 'beta');

// Authentication...
$app->add(new InitCommand());
$app->add(new BuildCommand);
$app->add(new SampleCommand);
$app->add(new SortContentCommand());

$app->run();
